
OBJS = time.h time.cpp obstacle.h obstacle.cpp biome.h biome.cpp player.h player.cpp main.cpp game.h game.cpp


OBJ_NAME = BoardON

all : $(OBJS)
	g++ -w -o $(OBJ_NAME) $(OBJS) -std=c++11 -lSDL2 -lSDL2_ttf